package:
  name: osx-opencl-variant
  version: 2.0

build:
  number: 0
  track_features:
    - osx_pocl_opencl  # [OSX_OPENCL_VARIANT=='pocl']
  string: {{ OSX_OPENCL_VARIANT }}
  skip: True  # [not osx]
  run_exports:
    - osx-opencl-variant 2.* {{ OSX_OPENCL_VARIANT }}

test: {}

outputs:
  # For backwards compatibility only. Remove when it's not used anymore
  - name: osx-pocl-opencl                                  # [OSX_OPENCL_VARIANT=='pocl']
    requirements:                                          # [OSX_OPENCL_VARIANT=='pocl']
       - osx-opencl-variant 2.* {{ OSX_OPENCL_VARIANT }}   # [OSX_OPENCL_VARIANT=='pocl']
    test: {}

about:
  home: http://github.com/conda-forge/osx-pocl-opencl-feedstock
  license: BSD 3-clause
  license_family: BSD
  summary: Metapackage to track whether OpenCL on OSX is being provided by POCL (rather than the OS)

extra:
  recipe-maintainers:
    - inducer
