travis:
  secure:
    BINSTAR_TOKEN: WfqUxMkFfVPrIViF9J/9gR8zJBXtVDwPoFeiEKkOiDZpFNgaESE1GSUMZNoBwVbPhik83MxTcwlKcx0vuB8wfTvLarNpXExtje3WuxS2VROe/OHRxDdqgZBdj1WdaNQh1qaaEnGcrSomFCKTfyr1P8tmO0JM6sQ3viemY4hOwI39vLR9zc5lsGGlmFhpTBY8wxMSFk6xk0VNiAH4fLgTFDizIO1Ws6YT4jrMFmnyEt/62FxaNS2jLukOh57A8tQsPWvO2PqM2aayMCGXSqn9NF6ZC7+YbeNfF4K5fV7hIPZRyLYF+IMVAXSZibavVDblB5C4vnqWLYOY1nQaFlhI0iqozDKbLrHM+ZB7KADdzlt3BIn6zqyZCcNG+XE3IeD9Pgtk5C7hvR0+O6emZ/+tm+AxlAuQ3GC1zSAkMHtrHOoweyuOwc+q3qWt0w3lTC2S0ltQFtFGvfT4k7ikxovP96D7xqjbnbjwLxmz3Z6BMOU0uu/8Z/fEyK353A+Z/NOu+5WOXQkA/gOn4GGB+jUoz+CFWk9nHFSS8DNwpwYMQbC9WwbmLVOuug+Q7kL3HaO8R9NSGFWiQJBKWYhlM21XFnQL56RAgdNxOvwdcHPLqUHugl7kQloZgZK5pcfwTO5Hh6O9q7cebhkukHoed9N0CR1EgQmM8rDxfSnXzzNw3FU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
