travis:
  secure:
    BINSTAR_TOKEN: qjoReVGmQJffH01uoZ1X03/mUwEJuY70CcTE9dIc2k3CbqZKSeRkxcYBh8SsUQ9sdb3ZfHBLNmKXjN33ixnjfsDcmeIsb3OyJy3uKken8ZL48+eD8F1W0OoImTtLBzuZBP6nSh3rkgxlxd+kzzm1HffXFcE9xuptw0Fl4gYqlNElPTi7S1LgM73WCnZV+8ZVeDPtEVS/UboJEvunLBG3DRmnL29O4raWPhaBpaafTN0UX0nK7ea/UeCmjtNzwJ9uKuPY7Dcr3z7AxeIXXdhliWKSMfNeJHzU4ckZhgOY8TbucZhbwzHPV10NPGKVJCiJQVKU8noU7UPg7JQV3w62WUdI6EtkQkfacwbiMUgXh41W1P2j29O3Kmm8dWXm4knnHefLYCv/3NE4GpN60ZKMd6baZfXPySzvDIs1b1sP98B4QXTvvMNemT3dfEcfCjRvl6iZTHY/PyBMuv4Q4Yn2ImhI2lsZWAWS0aP+wl5kD9gm5kolNiZnoRbI3k0AjjT46w5JTktuzrVuSm3Rt1YMl43Xvfz5QKctxkJXtiyBEBIStRtgIkf0deBp0lKvYQxPsC5rdxx/kqJE0O8IrwI8Ik2A0gAPfaeBDXrJZKVSkS0jbrfkjeX1byC5VyjyMok2ikNbmQ9k7lK/Hyg9Q/n7s+A4g2sSAxZPORP3qSo7KdI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
